platform :ios, '7.0'
pod "AFNetworking", "~>2.0"
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'UMengAnalytics'
pod 'AMap3DMap'
pod 'AMapSearch'